[package]
name = "fewtype"
version = "3.1.23"
description = "FewType 鐠囶參鐓舵径鍕倞楠炲啿褰?
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "fewtype_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
